version: "3"
services:
  app:
    container_name: mapa
    image: mapa-dc:latest
    ports:
      - "3000:13000"
    links:
      - "gdb"
    networks:
      - demo
  gdb:
    container_name: gdb
    image: zzglider/python-app:prc2021
    ports:
      - "7201:7200"
    links:
      - "gdb"
    networks:
      - demo
networks: 
  demo:
    name: demo
    driver: bridge
